[package]
name = "tictactoe"
version = "0.1.0"
authors = ["Robin Park <robin.j.park@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
